### ISSUE TITLE
How to use it in my JavaScript code?

### ISSUE THREAD

**Issue by limcheekin** [avirads/surrealdb_in_browser#1]
Hi there,

Thanks for sharing the repo.

From my understanding, the surrealdb.wasm (index.html) of your repo is able to run as static website such as hosted as GitHub Pages, correct me if I'm wrong. It is exactly what I looking for. :)

I managed to see the following in my browser console:
```
{memory: Memory(26), setup: ƒ, __wbg_surreal_free: ƒ, surreal_init: ƒ, surreal_connect: ƒ, …}
```

But I have no clue how the JavaScript code able to connect to the SurrealDB instance in the browser, I tried the following code:
```
import init, { Surreal } from "./surrealdb.js";
await init();

const db = new Surreal();

try {
  // Connect to the database
  await db.connect("ws://127.0.0.1:8000");
} catch (e) {
  console.error("ERROR", e);
}
``` 
It doesn't seems working.

Please advise. Thanks in advance.

**Comment by avirads** [comment]
hello,

a lot has happened since then and i have not been following all the
developments.

i would suggest checking this... https://github.com/surrealdb/surrealdb.wasm
their discord is really active. so someone can give you what you need
exactly over there.

regards,
avinash

**Comment by limcheekin** [comment]
Thanks for quick response. 

I'm facing similar error using their latest code then I found your repo. 

I post my question at https://github.com/orgs/surrealdb/discussions/2730
